// GENERATED by build_file_map.cjs — do not edit by hand.
// Extracted from BASE_PORTFOLIO + PORTFOLIO_VERSION in server/daily-cron.cjs,
// which is the authority. Regenerate with: npm run map

export interface Holding {
  ticker: string
  weight: number
  theme: string
  minWeight: number
  action: string
}

export interface Sleeve { name: string; weight: number }

export const BOOK = {
  version: "2026-09-30-v3.8-coinamzn",
  count: 12,
  total: 100,
  generatedAt: "2026-09-30T14:02:48.040Z",
  sleeves: [
  {
    "name": "Monetary",
    "weight": 27.5
  },
  {
    "name": "AI Buildout",
    "weight": 27.1
  },
  {
    "name": "Tokenized Rails",
    "weight": 24.1
  },
  {
    "name": "AI Applied",
    "weight": 21.3
  }
] as Sleeve[],
  holdings: [
  {
    "ticker": "LLY",
    "weight": 11.8,
    "theme": "AI Applied",
    "minWeight": 5.9,
    "action": "Trim"
  },
  {
    "ticker": "AMZN",
    "weight": 9.5,
    "theme": "AI Applied",
    "minWeight": 4.8,
    "action": "Trim"
  },
  {
    "ticker": "IBIT",
    "weight": 12.3,
    "theme": "Monetary",
    "minWeight": 6.2,
    "action": "Add"
  },
  {
    "ticker": "GLDM",
    "weight": 8,
    "theme": "Monetary",
    "minWeight": 4,
    "action": "Trim"
  },
  {
    "ticker": "ETHA",
    "weight": 9.1,
    "theme": "Tokenized Rails",
    "minWeight": 4.5,
    "action": "Trim"
  },
  {
    "ticker": "COIN",
    "weight": 7.5,
    "theme": "Tokenized Rails",
    "minWeight": 3.8,
    "action": "Add"
  },
  {
    "ticker": "HOOD",
    "weight": 7.5,
    "theme": "Tokenized Rails",
    "minWeight": 3.8,
    "action": "Hold"
  },
  {
    "ticker": "SLV",
    "weight": 7.2,
    "theme": "Monetary",
    "minWeight": 3.6,
    "action": "Trim"
  },
  {
    "ticker": "AIPO",
    "weight": 8.5,
    "theme": "AI Buildout",
    "minWeight": 4.2,
    "action": "Add"
  },
  {
    "ticker": "GLW",
    "weight": 5.5,
    "theme": "AI Buildout",
    "minWeight": 2.8,
    "action": "Trim"
  },
  {
    "ticker": "SOXX",
    "weight": 7,
    "theme": "AI Buildout",
    "minWeight": 3.5,
    "action": "Add"
  },
  {
    "ticker": "COPX",
    "weight": 6.1,
    "theme": "AI Buildout",
    "minWeight": 3,
    "action": "Trim"
  }
] as Holding[],
}
