// GENERATED by build_file_map.cjs — do not edit by hand.
// Extracted from BASE_PORTFOLIO + PORTFOLIO_VERSION in server/daily-cron.cjs,
// which is the authority. Regenerate with: npm run map

export interface Holding {
  ticker: string
  weight: number
  theme: string
  minWeight: number
  action: string
}

export interface Sleeve { name: string; weight: number }

export const BOOK = {
  version: "2026-08-31-v3.4.1-stageflip",
  count: 12,
  total: 100,
  generatedAt: "2026-09-09T19:44:50.918Z",
  sleeves: [
  {
    "name": "Monetary",
    "weight": 29.1
  },
  {
    "name": "AI Applied",
    "weight": 26.3
  },
  {
    "name": "AI Buildout",
    "weight": 24.8
  },
  {
    "name": "Tokenized Rails",
    "weight": 19.8
  }
] as Sleeve[],
  holdings: [
  {
    "ticker": "LLY",
    "weight": 13.9,
    "theme": "AI Applied",
    "minWeight": 7,
    "action": "Hold"
  },
  {
    "ticker": "AMZN",
    "weight": 12.4,
    "theme": "AI Applied",
    "minWeight": 6.2,
    "action": "Hold"
  },
  {
    "ticker": "IBIT",
    "weight": 12.2,
    "theme": "Monetary",
    "minWeight": 6.1,
    "action": "Add"
  },
  {
    "ticker": "GLDM",
    "weight": 9.1,
    "theme": "Monetary",
    "minWeight": 4.5,
    "action": "Add"
  },
  {
    "ticker": "ETHA",
    "weight": 11.8,
    "theme": "Tokenized Rails",
    "minWeight": 5.9,
    "action": "Add"
  },
  {
    "ticker": "HOOD",
    "weight": 8,
    "theme": "Tokenized Rails",
    "minWeight": 4,
    "action": "Add"
  },
  {
    "ticker": "SLV",
    "weight": 7.8,
    "theme": "Monetary",
    "minWeight": 3.9,
    "action": "Hold"
  },
  {
    "ticker": "AIPO",
    "weight": 6.2,
    "theme": "AI Buildout",
    "minWeight": 3.1,
    "action": "Trim"
  },
  {
    "ticker": "GLW",
    "weight": 5,
    "theme": "AI Buildout",
    "minWeight": 2.5,
    "action": "Hold"
  },
  {
    "ticker": "ASML",
    "weight": 5,
    "theme": "AI Buildout",
    "minWeight": 2.5,
    "action": "Trim"
  },
  {
    "ticker": "SOXX",
    "weight": 4.5,
    "theme": "AI Buildout",
    "minWeight": 2.2,
    "action": "Trim"
  },
  {
    "ticker": "COPX",
    "weight": 4.1,
    "theme": "AI Buildout",
    "minWeight": 2,
    "action": "Hold"
  }
] as Holding[],
}
