// GENERATED by build_file_map.cjs — do not edit by hand.
// Extracted from BASE_PORTFOLIO + PORTFOLIO_VERSION in server/daily-cron.cjs,
// which is the authority. Regenerate with: npm run map

export interface Holding {
  ticker: string
  weight: number
  theme: string
  minWeight: number
  action: string
}

export interface Sleeve { name: string; weight: number }

export const BOOK = {
  version: "2026-09-22-v3.6-ethabind",
  count: 11,
  total: 100,
  generatedAt: "2026-09-22T20:39:18.737Z",
  sleeves: [
  {
    "name": "Monetary",
    "weight": 28.8
  },
  {
    "name": "AI Applied",
    "weight": 26.2
  },
  {
    "name": "AI Buildout",
    "weight": 24.7
  },
  {
    "name": "Tokenized Rails",
    "weight": 20.3
  }
] as Sleeve[],
  holdings: [
  {
    "ticker": "LLY",
    "weight": 13.1,
    "theme": "AI Applied",
    "minWeight": 6.5,
    "action": "Hold"
  },
  {
    "ticker": "AMZN",
    "weight": 13.1,
    "theme": "AI Applied",
    "minWeight": 6.5,
    "action": "Hold"
  },
  {
    "ticker": "IBIT",
    "weight": 12.1,
    "theme": "Monetary",
    "minWeight": 6,
    "action": "Hold"
  },
  {
    "ticker": "GLDM",
    "weight": 9,
    "theme": "Monetary",
    "minWeight": 4.5,
    "action": "Hold"
  },
  {
    "ticker": "ETHA",
    "weight": 12.5,
    "theme": "Tokenized Rails",
    "minWeight": 6.2,
    "action": "Hold"
  },
  {
    "ticker": "HOOD",
    "weight": 7.8,
    "theme": "Tokenized Rails",
    "minWeight": 3.9,
    "action": "Add"
  },
  {
    "ticker": "SLV",
    "weight": 7.7,
    "theme": "Monetary",
    "minWeight": 3.9,
    "action": "Hold"
  },
  {
    "ticker": "AIPO",
    "weight": 7,
    "theme": "AI Buildout",
    "minWeight": 3.5,
    "action": "Add"
  },
  {
    "ticker": "GLW",
    "weight": 6.1,
    "theme": "AI Buildout",
    "minWeight": 3,
    "action": "Add"
  },
  {
    "ticker": "SOXX",
    "weight": 5.2,
    "theme": "AI Buildout",
    "minWeight": 2.6,
    "action": "Trim"
  },
  {
    "ticker": "COPX",
    "weight": 6.4,
    "theme": "AI Buildout",
    "minWeight": 3.2,
    "action": "Trim"
  }
] as Holding[],
}
