// GENERATED by build_file_map.cjs — do not edit by hand.
// Regenerate with:  npm run map
//
// State only. Meaning (stage mapping, roles, stale/orphan/proposed judgments)
// lives in systemMap.ts and is never derived here.

export interface FileState {
  exists: boolean
  tracked: boolean
  dirty: boolean
  /** matched by .gitignore — excluded on purpose, not by neglect */
  ignored?: boolean
  kind?: string
  sizeBytes?: number
  mtime?: string
  childCount?: number
  lastCommit?: string
  lastMessage?: string
  /** source files only — count of modules this one imports */
  imports?: number
  /** source files only — modules that import this one */
  importedBy?: string[]
  /** source files only — reachable from the Vite entry point */
  reachable?: boolean
}

export const MAP_META = {
  "generatedAt": "2026-09-28T22:53:07.885Z",
  "commit": "4c19845",
  "declared": 47,
  "missing": 3,
  "untracked": 0,
  "ignored": 3,
  "modified": 6,
  "undeclared": 1,
  "orphanedSource": 0,
  "undeclaredSource": 0
} as const

export const FILE_STATUS: Record<string, FileState> = {
  "signal_engine.py": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 23015,
    "mtime": "2026-07-16",
    "lastCommit": "2026-07-13",
    "lastMessage": "Engine v3.1: remove S4 (option-C weights); add MU/SKHY/MRVL to bottleneck axis; extend proximity carve-out to physical-s"
  },
  "signal_model_config.json": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 19205,
    "mtime": "2026-08-26",
    "lastCommit": "2026-07-13",
    "lastMessage": "Engine v3.1: remove S4 (option-C weights); add MU/SKHY/MRVL to bottleneck axis; extend proximity carve-out to physical-s"
  },
  "theme_engine.py": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 9310,
    "mtime": "2026-08-19",
    "lastCommit": "2026-08-19",
    "lastMessage": "L1: correct structural keys to real theme labels, re-anchor prior to v3.3"
  },
  "server/daily-cron.cjs": {
    "exists": true,
    "tracked": true,
    "dirty": true,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 94046,
    "mtime": "2026-09-28",
    "lastCommit": "2026-09-22",
    "lastMessage": "FREEZE 2026-09-22-v3.6-ethabind: ETHA working->binding (Visser 9/20 'we are finally at the point'). 11 names unchanged. "
  },
  "src/components/SignalRecap.tsx": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 21360,
    "mtime": "2026-08-17",
    "imports": 3,
    "importedBy": [
      "src/components/Dashboard.tsx"
    ],
    "reachable": true,
    "lastCommit": "2026-08-17",
    "lastMessage": "Voice cards 8/17: extract VOICES to src/data; Visser dates Stage 4 tokenization, Camillo BE drawdown re-rates entry, ZaS"
  },
  "src/data/voiceCards.ts": {
    "exists": true,
    "tracked": true,
    "dirty": true,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 12493,
    "mtime": "2026-09-28",
    "imports": 0,
    "importedBy": [
      "src/components/SignalRecap.tsx",
      "src/components/SystemTab.tsx"
    ],
    "reachable": true,
    "lastCommit": "2026-09-23",
    "lastMessage": "voiceCards: restore ZaStocks name in subtitle (dropped in 7698265)"
  },
  "Weekly_Workflow_v34_section.md": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 13675,
    "mtime": "2026-09-14",
    "lastCommit": "2026-09-14",
    "lastMessage": "workflow: protocol correction - transcripts are Project-files only, Claude runs the nomination sweep"
  },
  "pull_candidates.cjs": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 11331,
    "mtime": "2026-09-07",
    "lastCommit": "2026-09-07",
    "lastMessage": "voiceCards 2026-09-07 cycle: Visser 9/5-9/6, ZaStocks 9/1-9/7. Camillo stale, untouched. Add BSOL/GSOL to correlation + "
  },
  "conviction_tags.sql": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 2509,
    "mtime": "2026-07-15",
    "lastCommit": "2026-08-29",
    "lastMessage": "Track never-committed canonical files and spent v3.4 patch scripts"
  },
  "Conviction_Tagging_Rubric.docx": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 12217,
    "mtime": "2026-07-15",
    "lastCommit": "2026-08-29",
    "lastMessage": "Track never-committed canonical files and spent v3.4 patch scripts"
  },
  "conviction_tags.json": {
    "exists": false,
    "tracked": false,
    "dirty": false,
    "ignored": false,
    "kind": "file"
  },
  "severity_scores.json": {
    "exists": true,
    "tracked": false,
    "dirty": false,
    "ignored": true,
    "kind": "file",
    "sizeBytes": 983,
    "mtime": "2026-07-15"
  },
  "theme_engine_config.json": {
    "exists": false,
    "tracked": false,
    "dirty": false,
    "ignored": false,
    "kind": "file"
  },
  "theme_weights.json": {
    "exists": false,
    "tracked": false,
    "dirty": false,
    "ignored": false,
    "kind": "file"
  },
  "src/components/SignalRadar.tsx": {
    "exists": true,
    "tracked": true,
    "dirty": true,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 3949,
    "mtime": "2026-09-28",
    "imports": 1,
    "importedBy": [
      "src/components/SignalRecap.tsx"
    ],
    "reachable": true,
    "lastCommit": "2026-09-22",
    "lastMessage": "FREEZE 2026-09-22-v3.6-ethabind: ETHA working->binding (Visser 9/20 'we are finally at the point'). 11 names unchanged. "
  },
  "src/components/Portfolio.tsx": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 17696,
    "mtime": "2026-08-25",
    "imports": 2,
    "importedBy": [
      "src/components/Dashboard.tsx"
    ],
    "reachable": true,
    "lastCommit": "2026-08-24",
    "lastMessage": "UI: retheme signal cards for v3.4 trend names"
  },
  "Signal_Engine_Reference.md": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 9601,
    "mtime": "2026-07-15",
    "lastCommit": "2026-07-11",
    "lastMessage": "Remove S4 catalyst signal; lock composite to option C (S1/S2 .30); update engine docs"
  },
  "S1_Four_Axis_Spec.md": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 12476,
    "mtime": "2026-07-10",
    "lastCommit": "2026-07-11",
    "lastMessage": "Track current four-axis spec, live book doc, workflow, freeze patches"
  },
  "Weekly_Workflow original.md": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 7040,
    "mtime": "2026-07-06",
    "lastCommit": "2026-09-08",
    "lastMessage": "patches/ directory for patch scripts; workflow v34 rev 2026-09-07 with nomination sweep and coverage audit; packet secti"
  },
  "rescore_trendfirst.py": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 13492,
    "mtime": "2026-08-23",
    "lastCommit": "2026-08-23",
    "lastMessage": "v3.4 trend-first scoring: replace composite with timing x quality x wave x entry, breadth measured as N_eff from correla"
  },
  "Trend_First_Spec.md": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 6566,
    "mtime": "2026-08-23",
    "lastCommit": "2026-08-23",
    "lastMessage": "v3.4 trend-first scoring: replace composite with timing x quality x wave x entry, breadth measured as N_eff from correla"
  },
  "corr_matrix.json": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 17331,
    "mtime": "2026-09-07",
    "lastCommit": "2026-09-07",
    "lastMessage": "corr: 19 symbols/252 sessions, GSOL as SOL proxy (BSOL 215 closes truncated all series). Reinject worksheet"
  },
  "pull_correlations.py": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 2762,
    "mtime": "2026-09-07",
    "lastCommit": "2026-09-07",
    "lastMessage": "corr: 19 symbols/252 sessions, GSOL as SOL proxy (BSOL 215 closes truncated all series). Reinject worksheet"
  },
  "v34_worksheet.html": {
    "exists": true,
    "tracked": true,
    "dirty": true,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 86717,
    "mtime": "2026-09-28",
    "lastCommit": "2026-09-22",
    "lastMessage": "FREEZE 2026-09-22-v3.6-ethabind: ETHA working->binding (Visser 9/20 'we are finally at the point'). 11 names unchanged. "
  },
  "probe_source.textClipping": {
    "exists": true,
    "tracked": false,
    "dirty": false,
    "ignored": true,
    "kind": "file",
    "sizeBytes": 211,
    "mtime": "2026-07-27"
  },
  "src/data/systemMap.ts": {
    "exists": true,
    "tracked": true,
    "dirty": true,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 28883,
    "mtime": "2026-09-28",
    "imports": 0,
    "importedBy": [
      "src/components/SystemTab.tsx"
    ],
    "reachable": true,
    "lastCommit": "2026-09-22",
    "lastMessage": "FREEZE 2026-09-22-v3.6-ethabind: ETHA working->binding (Visser 9/20 'we are finally at the point'). 11 names unchanged. "
  },
  "system_changelog": {
    "exists": false,
    "tracked": false,
    "dirty": false,
    "kind": "table"
  },
  "src/main.tsx": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 230,
    "mtime": "2026-04-06",
    "imports": 2,
    "importedBy": [],
    "reachable": true,
    "lastCommit": "2026-04-06",
    "lastMessage": "initial commit"
  },
  "src/App.tsx": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 349,
    "mtime": "2026-04-08",
    "imports": 1,
    "importedBy": [
      "src/main.tsx"
    ],
    "reachable": true,
    "lastCommit": "2026-04-08",
    "lastMessage": "dashboard UI"
  },
  "src/components/Dashboard.tsx": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 26759,
    "mtime": "2026-09-25",
    "imports": 7,
    "importedBy": [
      "src/App.tsx",
      "src/components/IndicatorPanel.tsx",
      "src/components/PnLTracker.tsx",
      "src/components/Portfolio.tsx",
      "src/components/SignalRadar.tsx",
      "src/components/SignalRecap.tsx",
      "src/components/SystemTab.tsx",
      "src/components/TradingChart.tsx",
      "src/components/TradingTab.tsx"
    ],
    "reachable": true,
    "lastCommit": "2026-09-25",
    "lastMessage": "Stat cards: F&G shows band + probability pill, rename to CNN Fear & Greed Index / Inflation"
  },
  "src/components/SystemTab.tsx": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 29345,
    "mtime": "2026-09-18",
    "imports": 5,
    "importedBy": [
      "src/components/Dashboard.tsx"
    ],
    "reachable": true,
    "lastCommit": "2026-09-18",
    "lastMessage": "System tab reads the live snapshot: drifted sleeves vs frozen target, flag code/data version disagreement"
  },
  "src/data/fileStatus.ts": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 13790,
    "mtime": "2026-09-09",
    "imports": 0,
    "importedBy": [
      "src/components/SystemTab.tsx"
    ],
    "reachable": true,
    "lastCommit": "2026-09-09",
    "lastMessage": "System tab live: holdings from BASE_PORTFOLIO, voices from voiceCards, v3.4 cascade replaces v3.3 composite"
  },
  "src/data/bookSnapshot.ts": {
    "exists": true,
    "tracked": true,
    "dirty": true,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 2101,
    "mtime": "2026-09-28",
    "imports": 0,
    "importedBy": [
      "src/components/SystemTab.tsx"
    ],
    "reachable": true,
    "lastCommit": "2026-09-22",
    "lastMessage": "FREEZE 2026-09-22-v3.6-ethabind: ETHA working->binding (Visser 9/20 'we are finally at the point'). 11 names unchanged. "
  },
  "src/components/TradingTab.tsx": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 16041,
    "mtime": "2026-07-21",
    "imports": 7,
    "importedBy": [
      "src/components/Dashboard.tsx"
    ],
    "reachable": true,
    "lastCommit": "2026-07-21",
    "lastMessage": "Switch to Manrope everywhere (unified, incl. numbers); shrink Trading EW Phase card"
  },
  "src/components/TradingChart.tsx": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 12548,
    "mtime": "2026-07-22",
    "imports": 3,
    "importedBy": [
      "src/components/TradingTab.tsx"
    ],
    "reachable": true,
    "lastCommit": "2026-07-22",
    "lastMessage": "Fix empty last-price tag; add projected wave numbers, A label, and target distance filter"
  },
  "src/components/IndicatorPanel.tsx": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 3759,
    "mtime": "2026-07-21",
    "imports": 1,
    "importedBy": [
      "src/components/TradingTab.tsx"
    ],
    "reachable": true,
    "lastCommit": "2026-07-21",
    "lastMessage": "Trading tab: match stat-card font to site style, move indicators below chart (Option C auto-fit)"
  },
  "src/lib/elliott.ts": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 13188,
    "mtime": "2026-07-22",
    "imports": 1,
    "importedBy": [
      "src/components/TradingChart.tsx",
      "src/components/TradingTab.tsx"
    ],
    "reachable": true,
    "lastCommit": "2026-07-22",
    "lastMessage": "Fix empty last-price tag; add projected wave numbers, A label, and target distance filter"
  },
  "src/lib/technicals.ts": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 4325,
    "mtime": "2026-07-21",
    "imports": 0,
    "importedBy": [
      "src/components/TradingChart.tsx",
      "src/components/TradingTab.tsx",
      "src/lib/elliott.ts"
    ],
    "reachable": true,
    "lastCommit": "2026-07-20",
    "lastMessage": "Trading tab: BTC technical workbench (algo Elliott Wave, 50/200 MAs, anchored VWAP, volume profile, RSI, fib targets)"
  },
  "src/lib/indicator_docs.ts": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 3088,
    "mtime": "2026-07-21",
    "imports": 0,
    "importedBy": [
      "src/components/TradingTab.tsx"
    ],
    "reachable": true,
    "lastCommit": "2026-07-20",
    "lastMessage": "Trading tab: BTC technical workbench (algo Elliott Wave, 50/200 MAs, anchored VWAP, volume profile, RSI, fib targets)"
  },
  "build_file_map.cjs": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 16163,
    "mtime": "2026-09-18",
    "lastCommit": "2026-09-18",
    "lastMessage": "Book snapshot regenerates on every build; harden BASE_PORTFOLIO parse against padding"
  },
  ".gitignore": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 798,
    "mtime": "2026-09-08",
    "lastCommit": "2026-09-07",
    "lastMessage": "cycle_packet.py: read-only weekly state gather (queue item 16)"
  },
  ".github/workflows/daily-cron.yml": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 2351,
    "mtime": "2026-08-29",
    "lastCommit": "2026-08-29",
    "lastMessage": "Actually apply the backup cron patch"
  },
  ".env.local": {
    "exists": true,
    "tracked": false,
    "dirty": false,
    "ignored": true,
    "kind": "file",
    "sizeBytes": 612,
    "mtime": "2026-06-04"
  },
  "severity_probe.cjs": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 9912,
    "mtime": "2026-07-15",
    "lastCommit": "2026-08-29",
    "lastMessage": "Track never-committed canonical files and spent v3.4 patch scripts"
  },
  "probe_fear_guards.cjs": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 3053,
    "mtime": "2026-08-04",
    "lastCommit": "2026-08-29",
    "lastMessage": "Track never-committed canonical files and spent v3.4 patch scripts"
  },
  "src/components/PnLTracker.tsx": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 12699,
    "mtime": "2026-09-01",
    "imports": 2,
    "importedBy": [
      "src/components/Dashboard.tsx"
    ],
    "reachable": true,
    "lastCommit": "2026-09-01",
    "lastMessage": "UI: portfolio sizing input always shows 'Enter' placeholder (math unchanged, defaults 100k); Performance tab opens on eq"
  },
  "src/supabase.ts": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "ignored": false,
    "kind": "file",
    "sizeBytes": 238,
    "mtime": "2026-04-08",
    "imports": 0,
    "importedBy": [
      "src/components/Dashboard.tsx",
      "src/components/PnLTracker.tsx",
      "src/components/Portfolio.tsx",
      "src/components/TradingTab.tsx"
    ],
    "reachable": true,
    "lastCommit": "2026-04-08",
    "lastMessage": "add supabase"
  }
}

export const DECLARED_BUT_MISSING: string[] = [
  "conviction_tags.json",
  "theme_engine_config.json",
  "theme_weights.json"
]

export const UNDECLARED_UNTRACKED: string[] = [
  "v34_worksheet_2026-09-28.html"
]

/** exists under src/ but nothing reaches it from the entry point — dead code */
export const ORPHANED_SOURCE: string[] = []

/** reachable at runtime but absent from systemMap.ts — the map has a blind spot */
export const UNDECLARED_SOURCE: string[] = []
