// GENERATED by build_file_map.cjs — do not edit by hand.
// Regenerate with:  npm run map
//
// State only. Meaning (stage mapping, roles, stale/orphan/proposed judgments)
// lives in systemMap.ts and is never derived here.

export interface FileState {
  exists: boolean
  tracked: boolean
  dirty: boolean
  kind?: string
  sizeBytes?: number
  mtime?: string
  childCount?: number
  lastCommit?: string
  lastMessage?: string
}

export const MAP_META = {
  "generatedAt": "2026-08-19T13:18:55.284Z",
  "commit": "c58c465",
  "declared": 34,
  "missing": 3,
  "untracked": 9,
  "modified": 2,
  "undeclared": 6
} as const

export const FILE_STATUS: Record<string, FileState> = {
  "signal_engine.py": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 23015,
    "mtime": "2026-07-16",
    "lastCommit": "2026-07-13",
    "lastMessage": "Engine v3.1: remove S4 (option-C weights); add MU/SKHY/MRVL to bottleneck axis; extend proximity carve-out to physical-s"
  },
  "signal_model_config.json": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 19205,
    "mtime": "2026-07-15",
    "lastCommit": "2026-07-13",
    "lastMessage": "Engine v3.1: remove S4 (option-C weights); add MU/SKHY/MRVL to bottleneck axis; extend proximity carve-out to physical-s"
  },
  "theme_engine.py": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 7568,
    "mtime": "2026-08-05",
    "lastCommit": "2026-08-17",
    "lastMessage": "Track theme_engine.py: L1/L2 recommender, was living outside version control"
  },
  "server/daily-cron.cjs": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 93451,
    "mtime": "2026-08-04",
    "lastCommit": "2026-08-03",
    "lastMessage": "fear/greed: widen mid-sum guard to 0.95-1.06"
  },
  "src/components/SignalRecap.tsx": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 21360,
    "mtime": "2026-08-17",
    "lastCommit": "2026-08-17",
    "lastMessage": "Voice cards 8/17: extract VOICES to src/data; Visser dates Stage 4 tokenization, Camillo BE drawdown re-rates entry, ZaS"
  },
  "src/data/voiceCards.ts": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 19210,
    "mtime": "2026-08-17",
    "lastCommit": "2026-08-17",
    "lastMessage": "Voice cards 8/17: extract VOICES to src/data; Visser dates Stage 4 tokenization, Camillo BE drawdown re-rates entry, ZaS"
  },
  "Weekly_Workflow.md": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 7040,
    "mtime": "2026-07-06",
    "lastCommit": "2026-07-11",
    "lastMessage": "Track current four-axis spec, live book doc, workflow, freeze patches"
  },
  "pull_candidates.cjs": {
    "exists": true,
    "tracked": true,
    "dirty": true,
    "kind": "file",
    "sizeBytes": 10929,
    "mtime": "2026-08-11",
    "lastCommit": "2026-08-10",
    "lastMessage": "Fix: null-safe formatters for SKHY (no d50/d200 until Sept 18 / Apr 2027)"
  },
  "conviction_tags.sql": {
    "exists": true,
    "tracked": false,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 2509,
    "mtime": "2026-07-15"
  },
  "Conviction_Tagging_Rubric.docx": {
    "exists": true,
    "tracked": false,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 12217,
    "mtime": "2026-07-15"
  },
  "conviction_tags.json": {
    "exists": false,
    "tracked": false,
    "dirty": false,
    "kind": "file"
  },
  "severity_scores.json": {
    "exists": true,
    "tracked": false,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 983,
    "mtime": "2026-07-15"
  },
  "theme_engine_config.json": {
    "exists": false,
    "tracked": false,
    "dirty": false,
    "kind": "file"
  },
  "theme_weights.json": {
    "exists": false,
    "tracked": false,
    "dirty": false,
    "kind": "file"
  },
  "src/components/SignalRadar.tsx": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 3501,
    "mtime": "2026-07-23",
    "lastCommit": "2026-07-23",
    "lastMessage": "Sweep remaining serif/mono fonts to Manrope (SignalRadar themes + other components)"
  },
  "src/components/Portfolio.tsx": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 17409,
    "mtime": "2026-07-23",
    "lastCommit": "2026-07-23",
    "lastMessage": "Sweep remaining serif/mono fonts to Manrope (SignalRadar themes + other components)"
  },
  "Signal_Engine_Reference.md": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 9601,
    "mtime": "2026-07-15",
    "lastCommit": "2026-07-11",
    "lastMessage": "Remove S4 catalyst signal; lock composite to option C (S1/S2 .30); update engine docs"
  },
  "S1_Four_Axis_Spec.md": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 12476,
    "mtime": "2026-07-10",
    "lastCommit": "2026-07-11",
    "lastMessage": "Track current four-axis spec, live book doc, workflow, freeze patches"
  },
  "Weekly_Workflow_v2.docx": {
    "exists": true,
    "tracked": false,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 11974,
    "mtime": "2026-07-16"
  },
  "rescore_current_v3.py": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 5915,
    "mtime": "2026-07-06",
    "lastCommit": "2026-07-05",
    "lastMessage": "Three-axis S1 engine (offline): config block + s1_axes helper + rescore_v3 (score_ticker unchanged, cron untouched)"
  },
  "patch_gate_no_dma.py": {
    "exists": true,
    "tracked": false,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 1660,
    "mtime": "2026-08-11"
  },
  "probe_source.textClipping": {
    "exists": true,
    "tracked": false,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 211,
    "mtime": "2026-07-27"
  },
  "src/components/Methodology.tsx": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 18660,
    "mtime": "2026-07-23",
    "lastCommit": "2026-07-23",
    "lastMessage": "Sweep remaining serif/mono fonts to Manrope (SignalRadar themes + other components)"
  },
  "src/data/systemMap.ts": {
    "exists": true,
    "tracked": true,
    "dirty": true,
    "kind": "file",
    "sizeBytes": 31924,
    "mtime": "2026-08-19",
    "lastCommit": "2026-08-18",
    "lastMessage": "Tier C: derive file status from git, merge into System tab with declared-judgment precedence"
  },
  "system_changelog": {
    "exists": false,
    "tracked": false,
    "dirty": false,
    "kind": "table"
  },
  "src/components/Dashboard.tsx": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 16909,
    "mtime": "2026-08-15",
    "lastCommit": "2026-08-14",
    "lastMessage": "Add System tab: 3D pipeline graph with per-node history inspector (phase 1, constants)"
  },
  ".gitignore": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 783,
    "mtime": "2026-08-17",
    "lastCommit": "2026-08-17",
    "lastMessage": "gitignore: Finder artifacts, local asset folders, generated engine output"
  },
  ".github/workflows/": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "kind": "dir",
    "childCount": 1,
    "lastCommit": "2026-06-15",
    "lastMessage": "Change cron schedule time to 17:00 UTC"
  },
  ".env.local": {
    "exists": true,
    "tracked": false,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 612,
    "mtime": "2026-06-04"
  },
  "severity_probe.cjs": {
    "exists": true,
    "tracked": false,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 9912,
    "mtime": "2026-07-15"
  },
  "probe_fear_guards.cjs": {
    "exists": true,
    "tracked": false,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 3053,
    "mtime": "2026-08-04"
  },
  "src/components/PnLTracker.tsx": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 14325,
    "mtime": "2026-07-31",
    "lastCommit": "2026-07-31",
    "lastMessage": "PnLTracker: SPY Daily geometric, matching stored Thematic daily"
  },
  "src/supabase.ts": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 238,
    "mtime": "2026-04-08",
    "lastCommit": "2026-04-08",
    "lastMessage": "add supabase"
  },
  "src/components/HistoryLog.tsx": {
    "exists": true,
    "tracked": true,
    "dirty": false,
    "kind": "file",
    "sizeBytes": 11480,
    "mtime": "2026-07-23",
    "lastCommit": "2026-07-23",
    "lastMessage": "Sweep remaining serif/mono fonts to Manrope (SignalRadar themes + other components)"
  }
}

export const DECLARED_BUT_MISSING: string[] = [
  "conviction_tags.json",
  "theme_engine_config.json",
  "theme_weights.json"
]

export const UNDECLARED_UNTRACKED: string[] = [
  "patch_asof_tz.py",
  "patch_freeze_v31.py",
  "patch_freeze_v32.py",
  "patch_freeze_v33.py",
  "patch_mobile_ui.py",
  "patch_s5_null_guard.py"
]
